#
# This Source Code Form is subject to the terms of the Mozilla Public License, v.
# 2.0 with a Healthcare Disclaimer.
# A copy of the Mozilla Public License, v. 2.0 with the Healthcare Disclaimer can
# be found under the top level directory, named LICENSE.
# If a copy of the MPL was not distributed with this file, You can obtain one at
# http://mozilla.org/MPL/2.0/.
# If a copy of the Healthcare Disclaimer was not distributed with this file, You
# can obtain one at the project website https://github.com/igia.
#
# Copyright (C) 2021-2022 Persistent Systems, Inc.
#

#Local Postgres Data Source properties
app:
    datasource:
        postgresql:
            url: jdbc:postgresql://localhost:5432/clinical_data_infrastructure
            username: hip
            password: hip
            driver: org.postgresql.Driver

        #I2b2 Postgres meta Source properties
        i2b2-db-metainfo:
            demodataSchemaName: 
            metadataSchemaName: 
            
        i2b2demodata:
            url: jdbc:sqlserver://localhost:1432;databaseName=i2b2demodata
            username: i2b2demodata
            password: Demouser123
            driver: com.microsoft.sqlserver.jdbc.SQLServerDriver
            
        i2b2metadata:
            url: jdbc:sqlserver://localhost:1432;databaseName=i2b2metadata
            username: i2b2metadata
            password: Demouser123
            driver: com.microsoft.sqlserver.jdbc.SQLServerDriver
    
    logging:
        logstash:
            enabled: false
            host: 
            port: 5000
            queueSize: 512
            metricsEnabled: false
            
#SFTP Configuration Details
integration:
    sftp:
        remoteDirPathConcept: /concept/
        remoteDirPathData: /data/
        localDirPathConcept: /tmp/concept/
        localDirPathData: /tmp/data/
        host: localhost
        port: 2222
        user: i2b2sftpuser
        password: i2b2sftppass