#
# This Source Code Form is subject to the terms of the Mozilla Public License, v.
# 2.0 with a Healthcare Disclaimer.
# A copy of the Mozilla Public License, v. 2.0 with the Healthcare Disclaimer can
# be found under the top level directory, named LICENSE.
# If a copy of the MPL was not distributed with this file, You can obtain one at
# http://mozilla.org/MPL/2.0/.
# If a copy of the Healthcare Disclaimer was not distributed with this file, You
# can obtain one at the project website https://github.com/igia.
#
# Copyright (C) 2018-2019 Persistent Systems, Inc.
#

version: '3.2'
services:
    i2b2-cdi-postgresql:
        image: postgres:9.6.5
        container_name: i2b2-cdi-postgresql
        # volumes:
        #     - ~/volumes/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=igia
            - POSTGRES_PASSWORD=igiaPwd
            - POSTGRES_DB=clinical_data_infrastructure
        ports:
            - 4432:5432
